services:
  nginx:
    container_name: nginx-app
    image: nginx:alpine
    volumes:
      - ./notification/erro.html:/usr/share/nginx/html/index.html:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
    ports:
      - "8083:80"
