services:
  nginx:
    container_name: nginx-app
    image: nginx:alpine
    #./index.html:/usr/share/nginx/html/index.html:ro mapeia o arquivo index.html do diretório atual para o local padrão de arquivos HTML do Nginx dentro do container.
    #O sufixo ro indica que deve ser um arquivo read only
    volumes:
      - ../teste_scripts/Projeto/src/index.html:/usr/share/nginx/html/index.html:ro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1g
    ports:
      - "8083:80"
    command: ["nginx", "-g", "daemon off;"]